const menu = [
  {
    id: 1,
    title: "Margherita Pizza",
    category: "Pizza",
    price: 12.99,
    img: "item-1.jpg",
    desc: "Classic pizza with tomato sauce, mozzarella cheese, and fresh basil.",
  },
  {
    id: 2,
    title: "Spaghetti Carbonara",
    category: "Pasta",
    price: 14.99,
    img: "item-2.jpg",
    desc: "Creamy pasta dish with eggs, cheese, pancetta, and black pepper.",
  },
  {
    id: 3,
    title: "Grilled Salmon",
    category: "Seafood",
    price: 18.99,
    img: "item-3.jpg",
    desc: "Freshly grilled salmon fillet served with a lemon-dill sauce.",
  },
  {
    id: 4,
    title: "Caesar Salad",
    category: "Salad",
    price: 8.99,
    img: "item-4.jpg",
    desc: "Crisp romaine lettuce, croutons, parmesan cheese, and Caesar dressing.",
  },
  {
    id: 5,
    title: "Beef Burger",
    category: "Burgers",
    price: 10.99,
    img: "item-5.jpg",
    desc: "Juicy beef patty with lettuce, tomato, onion, and your choice of toppings.",
  },
  {
    id: 6,
    title: "Vegetable Stir-Fry",
    category: "Vegetarian",
    price: 13.99,
    img: "item-6.jpg",
    desc: "Assorted vegetables stir-fried with tofu in a savory sauce.",
  },
  {
    id: 7,
    title: "Chocolate Cake",
    category: "Dessert",
    price: 6.99,
    img: "item-7.jpg",
    desc: "Rich and moist chocolate cake served with a scoop of vanilla ice cream.",
  },
  {
    id: 8,
    title: "Iced Coffee",
    category: "Beverage",
    price: 3.99,
    img: "item-8.jpg",
    desc: "Chilled coffee with ice, sugar, and a touch of cream.",
  },
];
export default menu;
